name: 'update-version-selector'
description: 'Updates version selector'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  # selector-file-name:
  #   description: 'HTML file name'
  #   required: true
  # selector-id:
  #   description: 'select element id'
  #   required: true

runs:
  using: "composite"
  steps:
    - name: Discover versions
      shell: bash
      run: |
        git fetch origin gh-pages
        dirs=$(git ls-tree --name-only -d origin/gh-pages)

        mkdir selector-dir
        # Create HTML
        echo '<select id="versionSelector">' > selector-dir/version_selector.html
        for dir in $dirs; do
            if [[ "$(basename "$dir")" != .* ]]; then
                version=$(basename "$dir")
                echo "    <option value=\"$version\">$version</option>" >> selector-dir/version_selector.html
            fi
        done
        echo '</select>' >> selector-dir/version_selector.html

    - name: Deploy version_selector.html
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: selector-dir
        keep_files: true