name: 'build-docs'
description: 'Builds documentation using Doxygen'
inputs:
  cmake_target:
    description: 'CMake documentation target'
    required: true
  docs_dir:
    description: 'Path to documentation dir, relative to build_dir'
    required: true
  build_dir:
    description: 'Build directory'
    required: false
    default: 'build'
  cmake_configure_args:
    description: 'Additional CMake configure arguments'
    required: false
    default: ''

outputs:
  version:
    description: 'Version of the generated docs'
    value: ${{ steps.get-docs-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install deps
      shell: bash
      run:   |
              sudo apt install -y cmake
              sudo apt install -y wget
              wget -nv https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
              tar -xzf doxygen-1.10.0.linux.bin.tar.gz
              echo "$(pwd)/doxygen-1.10.0/bin" >> $GITHUB_PATH

    - name: CMake configuration
      shell: bash
      run:  cmake ${{ inputs.cmake_configure_args }} -B ${{ inputs.build_dir }}

    - name: CMake build
      shell: bash
      run:  cmake --build ${{ inputs.build_dir }} --target ${{ inputs.cmake_target }}

    - name: Get docs version
      id: get-docs-version
      shell: bash
      run: |
        subdir=$(basename $(find ${{ inputs.build_dir }}/${{ inputs.docs_dir }} -mindepth 1 -maxdepth 1 -type d | head -n 1))
        echo "version=$subdir" >> $GITHUB_OUTPUT
