name: 'build-docs'
description: 'Builds documentation using Doxygen'
inputs:
  build-dir:
    description: 'Build directory'
    required: true
outputs:
  docs-version:
    description: "Version of the generated docs"
    value: ${{ steps.get-docs-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install deps
      shell: bash
      run:   |
              sudo apt install -y cmake
              sudo apt install -y wget
              wget -nv https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
              tar -xzf doxygen-1.10.0.linux.bin.tar.gz
              echo "$(pwd)/doxygen-1.10.0/bin" >> $GITHUB_PATH

    - name: CMake configuration
      shell: bash
      run:  |
            cmake -B ${{ inputs.build-dir }}

    - name: CMake build
      shell: bash
      run:  |
            cmake --build ${{ inputs.build-dir }} --target doc

    - name: Get docs version
      id: get-docs-version
      shell: bash
      run: |
        subdir=$(basename $(find ${{ inputs.build-dir }}/doc/docs -mindepth 1 -maxdepth 1 -type d | head -n 1))
        echo "version=$subdir" >> $GITHUB_OUTPUT
