name: Create PR documentation

permissions:
  contents: write

# env:
#   SELECTOR_FILE_NAME: version_selector.html
#   SELECTOR_DIR: ${{github.workspace}}/version_selector
#   SELECTOR_FILE_PATH: $SELECTOR_DIR/$SELECTOR_FILE_NAME
#   SELECTOR_ID: versionSelector

on:
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main

jobs:
  create-pr-docs:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'documentation') }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build docs
        id: build-docs
        uses: ./.github/actions/build-docs
        with:
          cmake_target: 'doc'
          docs_dir: 'doc/docs'

      - name: Deploy PR docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doc/docs/${{ steps.build-docs.outputs.version }}
          destination_dir: PR-${{ github.event.pull_request.number }}

      - name: Update version selector
        uses: ./.github/actions/update-version-selector
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
