name: Create git-main docs

permissions:
  contents: write

env:
  BUILD_DIR: ${{github.workspace}}/build
  SELECTOR_FILE_NAME: version_selector.html
  SELECTOR_DIR: ${{github.workspace}}/version_selector
  SELECTOR_FILE_PATH: $SELECTOR_DIR/$SELECTOR_FILE_NAME
  SELECTOR_ID: versionSelector

on:
  push:
    branches:
      - main

jobs:
  create-git-main-docs:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build docs
        id: build-docs
        uses: ./.github/actions/build-docs
        with:
          cmake_target: 'doc'
          docs_dir: 'doc/docs'

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doc/docs/${{ steps.build-docs.outputs.version }}
          destination_dir: git-main

      - name: Update version selector
        id: update-version-selector
        uses: ./.github/actions/update-version-selector
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create redirect page if there are no releases
        if: ${{ steps.update-version-selector.outputs.versions_counter == 1}}
        uses: ./.github/actions/update-redirect-page
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: git-main/index.html