name: Create release documentation

permissions:
  contents: write

env:
  BUILD_DIR: ${{github.workspace}}/build
  SELECTOR_FILE_NAME: version_selector.html
  SELECTOR_DIR: ${{github.workspace}}/version_selector
  SELECTOR_FILE_PATH: $SELECTOR_DIR/$SELECTOR_FILE_NAME
  SELECTOR_ID: versionSelector

on:
  release:
    types: [released]

jobs:
  create-release-docs:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build docs
        id: build-docs
        uses: ./.github/actions/build-docs

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doc/docs/${{ steps.build-docs.outputs.version }}
          destination_dir: ${{ steps.build-docs.outputs.version }}

      - name: Update redirect HTML
        uses: ./.github/actions/update-redirect-page
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_url: ${{ steps.build-docs.outputs.version }}/index.html

      - name: Update version selector
        uses: ./.github/actions/update-version-selector
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}