name: Documentation workflow

permissions:
  contents: write

env:
  BUILD_DIR: ${{github.workspace}}/build
  SELECTOR_FILE_NAME: version_selector.html
  SELECTOR_ID: versionSelector
  GIT_USER_NAME: 'Oleksandr Koval'
  GIT_USER_EMAIL: 'OleksandrKvl@users.noreply.github.com'

on:
  # to update docs/git-main
  push:
    branches:
      - main
  # to publish docs/<release-version>
  release:
    types: [released]
  # to create and remove docs/PR<NUMBER>, can be triggered manually
  # pull_request:
  #   types: [opened, edited, closed]
  #   branches:
  #     - main

jobs:
  publish-docs:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build documentation
        id: build-docs
        uses: ./.github/actions/build-docs
        with:
          build-dir: $BUILD_DIR

      - name: Update redirect HTML
        if: github.event_name == 'release'
        uses: ./github/actions/generate-redirect-page
        with:
          output-file: $BUILD_DIR/doc/docs/index.html
          target-url: ${{ steps.build-docs.outputs.version }}/index.html

      - name: Deploy release docs
        if: github.event_name == 'release'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $BUILD_DIR/doc/docs
          destination_dir: ${{ steps.build-docs.outputs.version }}

      - name: Deploy git-main docs
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $BUILD_DIR/doc/docs/${{ steps.build-docs.outputs.version }}
          destination_dir: git-main

      - name: Update version selector
        uses: ./.github/actions/update-version-selector
        with:
          selector-file-name: $SELECTOR_FILE_NAME
          selector-id: $SELECTOR_ID
          user-name: '$GIT_USER_NAME'
          user-email: '$GIT_USER_EMAIL'

  publish-release-docs:
    runs-on: ubuntu-22.04
    if: false
    # if: github.event_name == 'release'

    steps:
      - id: build-docs
        uses: ./.github/actions/build-docs
        with:
          build-dir: $BUILD_DIR

      - name: Generate redirect HTML
        uses: ./github/actions/generate-redirect-page
        with:
          output-file: $BUILD_DIR/doc/docs/index.html
          target-url: ${{ steps.build-docs.outputs.version }}/index.html

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $BUILD_DIR/doc/docs
          destination_dir: ${{ steps.build-docs.outputs.version }}

      - name: Update version selector
        uses: ./.github/actions/update-version-selector
        with:
          selector-file-name: $SELECTOR_FILE_NAME
          selector-id: $SELECTOR_ID
          user-name: '$GIT_USER_NAME'
          user-email: '$GIT_USER_EMAIL'

  publish-git-main-docs:
    runs-on: ubuntu-22.04
    if: false
    # if: github.event_name == 'push'

    steps:
      - id: build-docs
        uses: ./.github/actions/build-docs
        with:
          build-dir: $BUILD_DIR

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $BUILD_DIR/doc/docs/${{ steps.build-docs.outputs.version }}
          destination_dir: git-main

      - name: Update version selector
        uses: ./.github/actions/update-version-selector
        with:
          selector-file-name: $SELECTOR_FILE_NAME
          selector-id: $SELECTOR_ID
          user-name: '$GIT_USER_NAME'
          user-email: '$GIT_USER_EMAIL'

# TODO: can we make steps depend on each other, to avoid their duplication?
# build-docs -> deploy -> update-version-selector
# I think we can create another action with optional destination_dir parameter
# then the only difference between them two will be redirect generation