name: Documentation workflow

permissions:
  contents: write

env:
  BUILD_DIR: ${{github.workspace}}/build
  SELECTOR_FILE_NAME: version_selector.html
  SELECTOR_DIR: ${{github.workspace}}/version_selector
  SELECTOR_FILE_PATH: $SELECTOR_DIR/$SELECTOR_FILE_NAME
  SELECTOR_ID: versionSelector

on:
  # to create and remove docs/PR<NUMBER>, can be triggered manually
  pull_request:
    types: [labeled, opened, edited, closed]
    branches:
      - main

jobs:
  publish-pr-docs:
    if: ${{ github.event.label.name == 'documentation' && github.event_name != 'closed' }}
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install deps
        shell: bash
        run:   |
                sudo apt install -y cmake
                sudo apt install -y wget
                wget -nv https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
                tar -xzf doxygen-1.10.0.linux.bin.tar.gz
                echo "$(pwd)/doxygen-1.10.0/bin" >> $GITHUB_PATH

      - name: CMake configure
        run:  cmake -B $BUILD_DIR

      - name: CMake build
        run:  cmake --build $BUILD_DIR --target doc

      - name: Get docs version
        id: get-docs-version
        run: |
          subdir=$(basename $(find $BUILD_DIR/doc/docs -mindepth 1 -maxdepth 1 -type d | head -n 1))
          echo "version=$subdir" >> $GITHUB_OUTPUT

      - name: Deploy PR docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BUILD_DIR }}/doc/docs/${{ steps.get-docs-version.outputs.version }}
          destination_dir: PR-${{ github.event.pull_request.number }}

      # Update version_selector.html
      - name: Pull gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Discover versions
        run: |
          mkdir $SELECTOR_DIR
          # Enumerate directories and store them in a variable
          dirs=$(find gh-pages -mindepth 1 -maxdepth 1 -type d | sort -rV)
      
          # Create HTML
          echo '<select id="${{ env.SELECTOR_ID }}">' > ${{ env.SELECTOR_FILE_PATH }}
          for dir in $dirs; do
              if [[ "$(basename "$dir")" != .* ]]; then
                  version=$(basename "$dir")
                  echo "    <option value=\"$version\">$version</option>" >> ${{ env.SELECTOR_FILE_PATH }}
              fi
          done
          echo '</select>' >> ${{ env.SELECTOR_FILE_PATH }}

      - name: Deploy version_selector.html
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.SELECTOR_DIR }}
          keep_files: true

  remove-pr-docs:
    if: ${{ github.event.label.name == 'documentation' && github.event_name == 'closed' }}
    runs-on: ubuntu-22.04
    
    steps:
      - name: Remove PR docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}
          destination_dir: PR-${{ github.event.pull_request.number }}