name: Documentation workflow

permissions:
  contents: write

on:
  # to update docs/git-main
  push:
    branches:
      - main
  # to publish docs/<release-version>
  release:
    types: [released]
  # to create and remove docs/PR<NUMBER>, can be triggered manually
  # pull_request:
  #   types: [opened, edited, closed]
  #   branches:
  #     - main

jobs:
  publish-release-docs:
    runs-on: ubuntu-22.04
    if: github.event_name == 'release'

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run:   |
              sudo apt install -y cmake
              sudo apt install -y wget
              wget -nv https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
              tar -xzf doxygen-1.10.0.linux.bin.tar.gz
              echo "$(pwd)/doxygen-1.10.0/bin" >> $GITHUB_PATH

    - name: CMake configuration
      run:  |
            cmake -B ${{github.workspace}}/build \
                  -D CMAKE_C_COMPILER=/usr/bin/gcc-11 \
                  -D CMAKE_CXX_COMPILER=/usr/bin/g++-11

    - name: CMake build
      run:  |
            cmake --build ${{github.workspace}}/build \
                  --target doc

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v4

      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/doc/docs
        keep_files: true

  publish-git-main-docs:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run:   |
              sudo apt install -y cmake
              sudo apt install -y wget
              wget -nv https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
              tar -xzf doxygen-1.10.0.linux.bin.tar.gz
              echo "$(pwd)/doxygen-1.10.0/bin" >> $GITHUB_PATH

    - name: CMake configuration
      run:  |
            cmake -B ${{github.workspace}}/build \
                  -D CMAKE_C_COMPILER=/usr/bin/gcc-11 \
                  -D CMAKE_CXX_COMPILER=/usr/bin/g++-11 \
                  -D MVDT_OVERRIDE_DOCS_DIR=git-main

    - name: CMake build
      run:  |
            cmake --build ${{github.workspace}}/build \
                  --target doc

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v4

      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{github.workspace}}/build/doc/docs/git-main
        destination_dir: git-main
    
    - name: Update version selector
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Enumerate Directories
      run: |
        # Enumerate directories and store them in a variable
        dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    
        # Create version_selector.html
        echo '<select id="versionSelector">' > version_selector.html
        for dir in $dirs; do
            version=$(basename "$dir")
            echo "    <option value=\"$version\">$version</option>" >> version_selector.html
        done
        echo '</select>' >> version_selector.html

    - name: Commit and Push version_selector.html
      run: |
        git config --global user.name 'Oleksandr Koval'
        git config --global user.email 'OleksandrKvl@users.noreply.github.com'
        git add version_selector.html
        git commit -m "Generate version_selector.html"
        git push origin gh-pages